### ISSUE TITLE
Fulfil response from Payee to Payer fails due to the `completedDate`

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-ledger#121]
## Scenario
Fulfil response from Payee to Payer fails due to the `completedDate`.

## Issue

Fulfil Handler fails with the following error due to the `completedDate` being null, as it was not provided in the incoming Transfer-Fulfil request:
```
2018-08-14T16:54:25.492Z - info: FulfilHandler::commit::validationPassed
Unhandled rejection Error: ER_BAD_NULL_ERROR: Column 'completedDate' cannot be null
    at Query.Sequence._packetToError (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/central-ledger/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/opt/central-ledger/node_modules/mysql/lib/Connection.js:208:25)
    at /opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/dialects/mysql/index.js:156:18
    at Promise._execute (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/dialects/mysql/index.js:150:12)
    at Client_MySQL.query (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/client.js:198:17)
    at /opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/transaction.js:274:21
    at tryCatcher (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/method.js:39:29)
    at Client_MySQL.trxClient.query (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/transaction.js:271:34)
    at Runner.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/runner.js:148:36)
    at Runner.tryCatcher (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/method.js:15:34)
    at /opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/knex/lib/runner.js:49:21
    at tryCatcher (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/opt/central-ledger/node_modules/@mojaloop/central-services-database/node_modules/bluebird/js/release/promise.js:614:10)
```

## Fix
The `completedDate` field is optional as per the Mojaloop v1 API Spec. 

I would also validate that the `fulfilment` & `extensionList` fields are  also optional. This should be similarly tested.

**Comment by elnyry** [comment]
@mdebarros I think we need to add a story as part of packaging to do some QA and testing the endpoints with only mandatory fields, this way we can cover issues similar to these. Let me add one and update it here

**Comment by elnyry** [comment]
Here is the item I created - https://github.com/mojaloop/project/issues/405

**Comment by elnyry** [comment]
This was fixed, don't remember the PR or issue used for tracking. Please re-open if this is observed again.
